model:
  mask: "fully_connected"      # Options: "fully_connected", "causal", "anti_causal", "skeleton", "cpdag"
  hidden_units: 64
  
objective:
  type: "eqrm"   # Options: "pseudo_ll", "maml", "irm", "vrex", "eqrm"
  inner_lr: 0.1       # For MAML
  inner_steps: 1      # number of inner‐loop steps
  maml_first_order: True
  lambda_penalty: 10 # weight for IRM / V-REx / EQRM penalty
  eqrm_tau: 0.75 # tau for EQRM

data:
  folder_path: "random_d20_k10_p03_disconnected"
  # graph_type: "random"
  # num_graphs: 10
  # num_vars: 10
  # num_categs: 10
  # edge_prob: 0.3
  size_obs: 1000
  size_int: 1000       # number of interv samples in total
  num_train_int: 14

training:
  epochs: 1000
  batch_size: 256
  optimizer: "adam"
  lr: 0.0001
  
evaluation:
  compute_bounds: True
  few_shot_num_samples: [1, 3, 10]
  few_shot_gradient_steps: 3
  few_shot_lr: 0.1

seed: 0
num_seeds: 2
wandb: False
