model:
  type: "causal"                # Options: "fully_connected", "causal", "anti_causal", "skeleton", "cpdag"
  hidden_units: 64
  
objective:
  type: "pseudo_ll"            # Options: "pseudo_ll", "maml", "irm"
  inner_lr: 0.1                # For MAML
  inner_steps: 1                 # number of inner‐loop steps
  maml_first_order: True

data:
  num_vars: 20
  output_dim: 10
  graph_type: "ER-1"           # Options: ER-1, ER-2, ER-3
  num_obs: 1000         # Number of observational samples
  num_int: 1000        # Number of interventional samples

training:
  epochs: 1000
  batch_size: 64
  optimizer: "adam"
  lr: 0.001
  
evaluation:
  compute_bounds: true
