model:
  type: "causal"      # Options: "fully_connected", "causal", "anti_causal", "skeleton", "cpdag"
  hidden_units: 64
  
objective:
  type: "pseudo_ll"   # Options: "pseudo_ll", "maml", "irm"
  inner_lr: 0.1       # For MAML
  inner_steps: 1      # number of inner‐loop steps
  maml_first_order: True

data:
  folder_path: "random_d10_k10_p03"
  size_obs: 500
  size_int: 500       # number of interv samples in total
  num_int: 7

training:
  epochs: 1000
  batch_size: 64
  optimizer: "adam"
  lr: 0.001
  
evaluation:
  compute_bounds: True
  few_shot_num_samples: [1, 3, 10, 30, 100]
  few_shot_gradient_steps: 3
  few_shot_lr: 0.1
